default_platform(:ios)

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_API_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_filepath: File.expand_path(ENV.fetch("APP_STORE_CONNECT_API_KEY_PATH")),
      in_house: false
    )
  end

  lane :upload do
    deliver(
      skip_binary_upload: true,
      skip_app_version_update: true,
      overwrite_screenshots: true,
      submit_for_review: false,
      force: true,
      precheck_include_in_app_purchases: false
    )
  end
end
